version: 3.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build:
    jobs:
      - myfirstbuild
jobs:
  myfirstbuild:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
