version: 3.1

workflows:
  version: 2
  build:
    jobs:
      - myfirstbuild

jobs:
  myfirstbuild:
    docker:
      — image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
